<?php

use Collection\MovieCollection;
use Collection\ShowTimeCollection;

if (!isset($movieCollection)) {
    $movieCollection = new MovieCollection([]);
}

if (!isset($showtimeCollection)) {
    $showtimeCollection = new ShowTimeCollection([]);
}

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie City</title>

    <link rel="stylesheet" type="text/css" href="../../web/login-me.css">
</head>
<body>
<?php include 'header.phtml'?>
<a href="movies">All Movies</a>
<p>Upcoming movies:</p>
<div>
    <ul>
        <?php foreach ($movieCollection as $movie) : ?>
            <img src="<?php echo $movie->getImage() ?>" style="width: 100px;"><br/>
            <li>
                <?php echo $movie->getName() . " (" . $movie->getYear() . ")"; ?>
                <ul>
                    <?php foreach ($showtimeCollection as $showtime) : ?>
                        <?php if ($showtime->getMovieId() === (int)$movie->getId()) : ?>
                            <li>
                                <?php echo $showtime->getDatetime() ?>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </li><br/>
        <?php endforeach; ?>
    </ul>
</div>
<?php include 'footer.phtml'?>
</body>
</html>

