<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie City</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <link href="https://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="../../web/style/login-template.css">
</head>
<body>
<div class="container bootstrap snippet">
    <div class="header">
        <ul class="nav nav-pills pull-right">
            <li><a href="home">Home</a></li>
            <li><a href="register">Register</a></li>
            <li class="active"><a href="login-template">Login</a></li>
        </ul>
        <h3 class="text-muted prj-name">Movie City</h3>
    </div>

    <div class="jumbotron" style="height:auto;min-height:300px;">
        <div class="col-md-4">
            <img src="https://bootdey.com/img/Content/Manbrown2.png" class="img-responsive center-block img-user">
        </div>
        <div class="col-md-6 form-content">
            <form class="form-horizontal" role="form" action="" method="post">
                <div class="form-group text-center">
                    <div class="col-sm-10 reg-icon">
                        <span class="fa fa-user fa-2x">Login</span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-10">
                        <input type="email" class="form-control" id="Username" placeholder="Username">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-10">
                        <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-info">
                            <span class="glyphicon glyphicon-share-alt"></span>
                            Login
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div style="text-align: center">
        <h2>This is just a presentational page</h2>
    </div>
</div>
</body>
</html>