<?php

use Collection\MovieCollection;

if (!isset($movieCollection)) {
    $movieCollection = new MovieCollection([]);
}

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie City</title>
</head>
<body>
<?php include 'header.phtml'?>
<a href="home">Home</a>
<p>All movies:</p>
<div>
    <ul>
        <?php foreach ($movieCollection as $movie) : ?>
            <img src="<?php echo $movie->getImage()?>" style="width: 100px;"><br/>
            <li>
                <?php echo $movie->getName() . " (" . $movie->getYear() . ")";?>
            </li><br/>
        <?php endforeach;?>
    </ul>
</div>
<?php include 'footer.phtml'?>
</body>
</html>